language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: .vuepress/dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
